// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Returns the health status of the API, including uptime and current timestamp",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "Service is healthy",
                        "schema": {
                            "$ref": "#/definitions/health.healthResponse"
                        }
                    },
                    "503": {
                        "description": "Service is unhealthy",
                        "schema": {
                            "$ref": "#/definitions/health.healthResponse"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "Returns the health status of the API, including uptime and current timestamp",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "Service is healthy",
                        "schema": {
                            "$ref": "#/definitions/health.healthResponse"
                        }
                    },
                    "503": {
                        "description": "Service is unhealthy",
                        "schema": {
                            "$ref": "#/definitions/health.healthResponse"
                        }
                    }
                }
            }
        },
        "/live": {
            "get": {
                "description": "Returns the health status of the API, including uptime and current timestamp",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "Service is healthy",
                        "schema": {
                            "$ref": "#/definitions/health.healthResponse"
                        }
                    },
                    "503": {
                        "description": "Service is unhealthy",
                        "schema": {
                            "$ref": "#/definitions/health.healthResponse"
                        }
                    }
                }
            }
        },
        "/ready": {
            "get": {
                "description": "Returns the health status of the API, including uptime and current timestamp",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "Service is healthy",
                        "schema": {
                            "$ref": "#/definitions/health.healthResponse"
                        }
                    },
                    "503": {
                        "description": "Service is unhealthy",
                        "schema": {
                            "$ref": "#/definitions/health.healthResponse"
                        }
                    }
                }
            }
        },
        "/rooms": {
            "post": {
                "security": [
                    {
                        "MemberAuth": []
                    }
                ],
                "description": "Creates a new chat room with the specified settings and returns room details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rooms"
                ],
                "summary": "Create a new chat room",
                "parameters": [
                    {
                        "description": "Room creation parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rooms.createRoomRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Room created successfully",
                        "schema": {
                            "$ref": "#/definitions/rooms.createRoomResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - validation error or room full",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized - missing authentication",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "Conflict - room already exists or user already in room",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/rooms/{roomId}": {
            "get": {
                "security": [
                    {
                        "MemberAuth": []
                    }
                ],
                "description": "Retrieves room information including messages and members",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rooms"
                ],
                "summary": "Get room details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room ID",
                        "name": "roomId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Room details",
                        "schema": {
                            "$ref": "#/definitions/rooms.roomResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - missing room ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized - not a member",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Room not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "MemberAuth": []
                    }
                ],
                "description": "Permanently deletes a room and all its messages (owner only)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rooms"
                ],
                "summary": "Delete a chat room",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room ID",
                        "name": "roomId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Room deleted successfully"
                    },
                    "400": {
                        "description": "Bad request - missing room ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized - not owner or not member",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Room not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/rooms/{roomId}/boot": {
            "post": {
                "security": [
                    {
                        "MemberAuth": []
                    }
                ],
                "description": "Removes a user from the room (owner only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rooms"
                ],
                "summary": "Boot a user from room",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room ID",
                        "name": "roomId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User to boot",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rooms.bootUserRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "User booted successfully"
                    },
                    "400": {
                        "description": "Bad request - cannot boot yourself",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized - not owner or not member",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Room or member not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/rooms/{roomId}/join": {
            "get": {
                "security": [
                    {
                        "MemberAuth": []
                    }
                ],
                "description": "Establishes WebSocket connection to join a chat room with the provided join code",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rooms"
                ],
                "summary": "Join a chat room via WebSocket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room ID",
                        "name": "roomId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Join code for the room",
                        "name": "joinCode",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Username to join with",
                        "name": "username",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "101": {
                        "description": "Switching Protocols - WebSocket connection established",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad request - missing parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized - authentication failed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Room not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/rooms/{roomId}/leave": {
            "post": {
                "security": [
                    {
                        "MemberAuth": []
                    }
                ],
                "description": "Removes the current user from the room",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rooms"
                ],
                "summary": "Leave a chat room",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room ID",
                        "name": "roomId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Left room successfully"
                    },
                    "400": {
                        "description": "Bad request - missing room ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized - not a member",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Room or member not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/rooms/{roomId}/messages": {
            "post": {
                "security": [
                    {
                        "MemberAuth": []
                    }
                ],
                "description": "Creates a new message in the specified room and broadcasts it to all connected clients. Messages are persisted only if the room is persistent.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "Create a new message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room ID",
                        "name": "roomId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Message content",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/messages.createMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Message created successfully",
                        "schema": {
                            "$ref": "#/definitions/messages.createMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - validation error or missing room ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized - missing authentication or not a member",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Room not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/rooms/{roomId}/messages/{messageId}": {
            "delete": {
                "security": [
                    {
                        "MemberAuth": []
                    }
                ],
                "description": "Deletes a message from the room. Only available for persistent rooms.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "Delete a message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room ID",
                        "name": "roomId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Message ID",
                        "name": "messageId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Message deleted successfully"
                    },
                    "400": {
                        "description": "Bad request - missing room ID or message ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized - missing authentication or not a member",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Room or message not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "health.healthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "description": "Health status (ok or unhealthy)",
                    "type": "string",
                    "example": "ok"
                },
                "timestamp": {
                    "description": "Current server timestamp in RFC3339 format",
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                },
                "uptime": {
                    "description": "Server uptime since start",
                    "type": "string",
                    "example": "2h30m45s"
                }
            }
        },
        "messages.createMessageRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "Message content",
                    "type": "string",
                    "maxLength": 5000,
                    "minLength": 1,
                    "example": "Hello, everyone!"
                },
                "roomId": {
                    "description": "Room ID",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440003"
                }
            }
        },
        "messages.createMessageResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "Message content",
                    "type": "string",
                    "example": "Hello, everyone!"
                },
                "id": {
                    "description": "Unique message identifier",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440003"
                },
                "roomId": {
                    "description": "Room identifier where message was sent",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "rooms.bootUserRequest": {
            "type": "object",
            "properties": {
                "memberId": {
                    "description": "Member ID to remove",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440001"
                }
            }
        },
        "rooms.createRoomRequest": {
            "type": "object",
            "properties": {
                "persistent": {
                    "description": "Whether the room persists after all users leave",
                    "type": "boolean",
                    "example": true
                },
                "username": {
                    "description": "Username of the room creator",
                    "type": "string",
                    "minLength": 1,
                    "example": "john_doe"
                }
            }
        },
        "rooms.createRoomResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "Room creation timestamp",
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                },
                "joinCode": {
                    "description": "Code required to join the room",
                    "type": "string",
                    "example": "ABC123"
                },
                "persistent": {
                    "description": "Whether the room is persistent",
                    "type": "boolean",
                    "example": true
                },
                "roomId": {
                    "description": "Unique room identifier",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "rooms.messageResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "Message content",
                    "type": "string",
                    "example": "Hello, world!"
                },
                "id": {
                    "description": "Unique message identifier",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440003"
                },
                "user": {
                    "description": "User who sent the message",
                    "allOf": [
                        {
                            "$ref": "#/definitions/rooms.userResponse"
                        }
                    ]
                }
            }
        },
        "rooms.roomResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "Room creation timestamp",
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                },
                "id": {
                    "description": "Unique room identifier",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "joinCode": {
                    "description": "Code required to join the room",
                    "type": "string",
                    "example": "ABC123"
                },
                "messages": {
                    "description": "List of messages in the room",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rooms.messageResponse"
                    }
                },
                "owner": {
                    "description": "Room owner information",
                    "allOf": [
                        {
                            "$ref": "#/definitions/rooms.userResponse"
                        }
                    ]
                },
                "persistent": {
                    "description": "Whether the room is persistent",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "rooms.userResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "Unique user identifier",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440002"
                },
                "name": {
                    "description": "Username",
                    "type": "string",
                    "example": "john_doe"
                }
            }
        }
    },
    "securityDefinitions": {
        "MemberAuth": {
            "type": "apiKey",
            "name": "member_id",
            "in": "cookie"
        }
    },
    "tags": [
        {
            "description": "Room management operations",
            "name": "rooms"
        },
        {
            "description": "Message operations",
            "name": "messages"
        },
        {
            "description": "Health check endpoints",
            "name": "health"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Visper API",
	Description:      "Anonymous chat room API with WebSocket support",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
